apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: agent
      port: 50000
      targetPort: 50000
      nodePort: 30001
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30002
  selector:
    app: jenkins
