apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: myjenkins-blueocean:latest2
        ports:
        - containerPort: 8080
        - containerPort: 50000
        - containerPort: 22
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: jenkins-docker-certs
          mountPath: /certs/client
          readOnly: true
        env:
        - name: DOCKER_HOST
          value: "tcp://docker:2376"
        - name: DOCKER_CERT_PATH
          value: "/certs/client"
        - name: DOCKER_TLS_VERIFY
          value: "1"
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-data
      - name: jenkins-docker-certs
        persistentVolumeClaim:
          claimName: jenkins-docker-certs
